nvme_mount_point: "/mnt/data"

k8s:
  version: "1.33.2"
  cgroup_driver: "systemd"
  pod_network_cidr: "10.244.0.0/16"
  service_cidr: "10.96.0.0/12"


base_os:
  common_packages:
    - vim
    - curl
    - wget
    - git
    - net-tools
    - htop

  firewalld_services:
    - ssh
    - http

  enable_epel: true
  manage_selinux: true
  selinux_state: permissive



libvirt:
  packages:
    - qemu-kvm
    - libvirt
    - virt-install
    - bridge-utils
    - libvirt-daemon-config-network
    - virt-manager

  user: "{{ ansible_user | default('adnan') }}"

  enable_bridged_network: true
  bridge_name: br-lan

  networks:
    # Default network (predefined on most libvirt systems)
    - name: default
      state: active
      autostart: true

    # Custom network we'll generate from XML
    - name: virbr-lan
      state: active
      autostart: true
      xml_content: |
        <network>
          <name>virbr-lan</name>
          <forward mode="bridge"/>
          <bridge name="br-lan" />
        </network>


vms:
  - name: pfsense
    state: running
    autostart: true
    memory_mb: 2048
    vcpus: 2
    disks:
      - name: pfsense-root.qcow2
        size: 20
        pool: default
    cdrom: "{{ nvme_mount_point }}/iso/netgate-installer-amd64.iso"
    networks:
      - network: virbr-lan
      - network: default
